/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#191c1f",
        "background": "#f7fafa",
        "on-surface": "#181c1d",
        "surface-container": "#ebeeee",
        "on-secondary": "#ffffff",
        "outline": "#707979",
        "surface-variant": "#e0e3e3",
        "inverse-primary": "#a1cfd3",
        "tertiary": "#58331d",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#f4ba9d",
        "surface-container-high": "#e6e9e9",
        "on-tertiary-container": "#f4bb9d",
        "on-secondary-container": "#606366",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#1f4d51",
        "secondary": "#5c5f62",
        "secondary-fixed-dim": "#c5c6ca",
        "secondary-container": "#dee0e4",
        "outline-variant": "#c0c8c9",
        "surface-tint": "#396569",
        "primary-container": "#2d5a5e",
        "on-primary-fixed": "#002022",
        "surface-container-low": "#f1f4f4",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eef1f1",
        "primary-fixed": "#bcebef",
        "primary-fixed-dim": "#a1cfd3",
        "on-tertiary-fixed-variant": "#653d27",
        "on-primary-container": "#a2d0d4",
        "on-background": "#181c1d",
        "surface-dim": "#d7dbdb",
        "surface-bright": "#f7fafa",
        "secondary-fixed": "#e1e2e6",
        "tertiary-container": "#734932",
        "on-tertiary-fixed": "#311303",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdbca",
        "inverse-surface": "#2d3131",
        "on-secondary-fixed-variant": "#44474a",
        "surface-container-highest": "#e0e3e3",
        "error-container": "#ffdad6",
        "primary": "#124346",
        "surface": "#f7fafa",
        "on-surface-variant": "#404849",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
